version: "2"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - /misdatos/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: usuario
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: rest
      MYSQL_ROOT_PASSWORD: 1234
  web:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./:/opt/data 
    depends_on:
      - mysql
